[app]
overall = { bg = "#332222" }

[mgr]
cwd = { fg = "#efb26c" }
find_keyword = { fg = "#ef7d6c", bold = true }

marker_copied = { bg = "#50b16d" }
marker_cut = { bg = "#e36778" }
#marker_marked = { bg = "#000000" }
marker_selected = { bg = "#efb26c" }

count_copied = { bg = "#50b16d", fg = "#2a1b1b", bold = true }
count_cut = { bg = "#e36778", fg = "#2a1b1b", bold = true }
count_selected = { bg = "#efb26c", fg = "#2a1b1b", bold = true }

border_style = { fg = "#863b2f" }

[indicator]
parent = { bg = "#863b2f", fg = "#2a1b1b", bold = true }
current = { bg = "#efb26c", fg = "#2a1b1b", bold = true } # by default this has different colors for file/dir, not sure how to replicate
preview = { bg = "#863b2f", fg = "#2a1b1b", bold = true }
padding = { open = "ğŸ­…", close = "ğŸ­¡" }

[tabs]
active = { bg = "#c25e50", fg = "#2a1b1b", bold = true }
inactive = { bg = "#2a1b1b", fg = "#c25e50", bold = true }
sep_inner = { open = "ğŸ­…", close = "ğŸ­¡" }
sep_outer = { open = "â–ˆ", close = "ğŸ­¡" }

[status]
sep_left = { open = "â–ˆ", close = "ğŸ­¡" }
sep_right = { open = "ğŸ­…", close = "â–ˆ" }
overall = { bg = "#4b1b22", fg = "#efb26c" }

perm_type = { fg = "#948add" }
perm_read = { fg = "#efb26c" }
perm_write = { fg = "#e36778" }
perm_exec = { fg = "#b2d75c" }
perm_sep = { fg = "#986e3f" }

progress_label  = { bold = true, fg = "#efb26c" }
progress_normal = { fg = "#6d2a20", bg = "#2a1b1b" }
progress_error  = { fg = "#2a1b1b", bg = "#e36778" }

[filetype]
rules = [
    # Media
    { mime = "image/webp", fg = "#7f51a7" },
    { mime = "image/*", fg = "#a374cb" },
    { mime = "{audio,video}/*", fg = "#c95b8d" },
    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#50b16d" },
    # Docs
    { mime = "application/{pdf,doc,rtf,xls,docx,xlsx}", fg = "#5da6b9" },


    # Empty file
	{ mime = "inode/empty", fg = "#b4b4b4" },
    # Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#666666" },
	# Orphan symbolic links
	{ url = "*", is = "orphan", bg = "#666666" },
    # Executables
	{ url = "*", is = "exec"  , fg = "#b2d75c" },
	# Dummy file
	{ url = "*", is = "dummy", bg = "#e36778" },
	{ url = "*/", is = "dummy", bg = "#e36778" },
	# All directories
	{ url = "*/", fg = "#ef7d6c" }
]

[icon]
# Icons mapped to unicode codepoints, see https://www.nerdfonts.com/cheat-sheet
# See also for inspiration: https://github.com/sxyazi/yazi/blob/97d0c6bb23df413f4add8b888071233c912c49a3/yazi-config/preset/theme-dark.toml
globs = []
dirs = [
    { name = "ciqven", text = "ğŸ¦Š", fg = "#986e3f" },
	{ name = ".config", text = "î—¼", fg = "#986e3f" },
	{ name = ".git", text = "î—»", fg = "#986e3f" },
	{ name = ".github", text = "î—½", fg = "#986e3f" },
	{ name = ".npm", text = "î—º", fg = "#986e3f" },
	{ name = "Desktop", text = "ï„ˆ", fg = "#efb26c" },
	{ name = "Development", text = "ï„¡", fg = "#efb26c" },
    { name = "Projects", text = "ï„¡", fg = "#efb26c" },
    { name = "Programs", text = "î®", fg = "#efb26c" },
	{ name = "Documents", text = "ó°ˆ™", fg = "#efb26c" },
	{ name = "Downloads", text = "ó°‡š", fg = "#efb26c" },
    { name = "Games", text = "ó°Š–", fg = "#efb26c" },
	{ name = "Library", text = "î®œ", fg = "#efb26c" },
	{ name = "Movies", text = "ï‘‡", fg = "#efb26c" },
	{ name = "Music", text = "ï€¥", fg = "#efb26c" },
	{ name = "Pictures", text = "î‰„", fg = "#efb26c" },
	{ name = "Public", text = "ï«", fg = "#efb26c" },
	{ name = "Videos", text = "ï‘‡", fg = "#efb26c" },
]
conds = [
    { if = "orphan", text = "ï±" },
	{ if = "link", text = "ï’" },
	{ if = "block", text = "ïƒ‰" },
	{ if = "char", text = "ï‡€" },
	{ if = "fifo", text = "ï‡‘" },
	{ if = "sock", text = "ï‡¤" },
	{ if = "sticky", text = "ï‡¼" },
	{ if = "dummy", text = "ï—" },

    { if = "hidden & dir", text = "î—¿", fg = "#986e3f" },
    { if = "dir", text = "î—¿", fg = "#efb26c" },
    # Normal files
    { if = "!(dir | link)", text = "ï…›", fg = "#efb26c" },
]